### ISSUE TITLE
Pre-refactoring ToDo-List

### ISSUE THREAD

**Issue by AtiX** [ad-si/brickify#278]
- [x] merge #265 and 3d print shadow, line of sight into dev (Arthur)
- [x] merge legoVisualizer into newLayouter (Yannis)
- [x] merge newLayouter into dev (Yannis + Arthur)
- [ ] create ppt slide deck (see #226 ) (Yannis + Stefan)
- [ ] review meshlib and use updated version (everybody)
- [x] merge state refactoring into dev (Stefan)
- [x] Create a Release (everybody)
- [ ] Refactor ALL THE THINGS (everybody)

![2015-02-25 refactoring planning](https://cloud.githubusercontent.com/assets/236678/6369056/f4724e6a-bce2-11e4-8d37-fbcde0c8ef1f.jpg)
